[package]
name = "risc0-build"
version = "0.11.1"
edition = "2021"
description = "RISC Zero zero-knowledge VM build tool"
license = "Apache-2.0"
homepage = "https://risczero.com/"
repository = "https://github.com/risc0/risc0/"

[dependencies]
cargo_metadata = "0.15"
reqwest = { version = "0.11", features = ["rustls-tls", "blocking"] }
risc0-zkvm = "0.11"
risc0-zkvm-platform-sys = "0.11"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
zip = "0.6"
